export default [
  {
    href: "/docs",
    target: "_self",
    sub: false,
    label: "欢迎阅读文档！",
  },
  {
    href: "/docs/playground",
    target: "_self",
    sub: false,
    label: "演练场",
  },
  {
    label: "安装",
  },
  {
    href: "/docs/installation/installer-linux",
    target: "_self",
    sub: true,
    label: "安装程序 (GNU/Linux)",
  },
  {
    href: "/docs/installation/installer-windows",
    target: "_self",
    sub: true,
    label: "安装程序 (Windows Server)",
  },
  {
    href: "/docs/installation/debian",
    target: "_self",
    sub: true,
    label: "Debian/Ubuntu",
  },
  {
    href: "/docs/installation/rpm",
    target: "_self",
    sub: true,
    label: "RHEL/Fedora",
  },
  {
    href: "/docs/installation/docker",
    target: "_self",
    sub: true,
    label: "Docker",
  },
  {
    href: "/docs/installation/package-managers",
    target: "_self",
    sub: true,
    label: "包管理器 (社区)",
  },
  {
    href: "/docs/installation/manual",
    target: "_self",
    sub: true,
    label: "手动安装",
  },
  {
    label: "常见用例",
  },
  {
    href: "/docs/use-cases/static-file-serving",
    target: "_self",
    sub: true,
    label: "静态文件服务",
  },
  {
    href: "/docs/use-cases/reverse-proxy",
    target: "_self",
    sub: true,
    label: "反向代理",
  },
  {
    href: "/docs/use-cases/php",
    target: "_self",
    sub: true,
    label: "PHP 托管",
  },
  {
    href: "/docs/use-cases/web-applications",
    target: "_self",
    sub: true,
    label: "Web 应用程序",
  },
  {
    href: "/docs/use-cases/redirecting",
    target: "_self",
    sub: true,
    label: "重定向",
  },
  {
    label: "参考",
  },
  {
    href: "/docs/configuration-kdl",
    target: "_self",
    sub: true,
    label: "服务器配置",
  },
  {
    href: "/docs/configuration",
    target: "_self",
    sub: true,
    label: "服务器配置 (旧版)",
  },
  {
    href: "/docs/modules",
    target: "_self",
    sub: true,
    label: "服务器模块",
  },
  {
    href: "/docs/observability",
    target: "_self",
    sub: true,
    label: "可观察性后端",
  },
  {
    href: "/docs/automatic-tls",
    target: "_self",
    sub: true,
    label: "自动 TLS",
  },
  {
    href: "/docs/commands",
    target: "_self",
    sub: true,
    label: "命令",
  },
  {
    href: "/docs/ferrbench",
    target: "_self",
    sub: true,
    label: "FerrBench",
  },
  {
    href: "https://rustdocs-v2.ferron.sh",
    target: "_self",
    sub: true,
    label: "Rust crate 文档",
  },
  {
    href: "https://v1.ferron.sh/docs",
    target: "_self",
    sub: true,
    label: "Ferron 1.x 文档",
  },
];
