site_name: Ferron 中文文档
docs_dir: docs_zh
custom_domain: ferron.ooos.top
site_author: Jetsung Chan
edit_uri: edit/docs/docs_zh
copyright: Copyright &copy; 2025 Jetsung Chan

theme:
  name: material
  navigation:
    expand: true
    sections: true

nav:
    - 首页: index.md
    - 演练场: playground.md
    - 安装:
        - Debian: installation/debian.md
        - Docker: installation/docker.md
        - Linux 安装器: installation/installer-linux.md
        - Windows 安装器: installation/installer-windows.md
        - 手动安装: installation/manual.md
        - 包管理器: installation/package-managers.md
        - RPM: installation/rpm.md
    - 使用案例:
        - PHP: use-cases/php.md
        - 重定向: use-cases/redirecting.md
        - 反向代理: use-cases/reverse-proxy.md
        - 静态文件服务: use-cases/static-file-serving.md
        - Web 应用: use-cases/web-applications.md
    - 自动TLS: automatic-tls.md
    - 命令: commands.md
    - 配置: configuration.md
    - 配置 (KDL): configuration-kdl.md
    - 性能测试: ferrbench.md
    - 模块: modules.md
    - 可观测性: observability.md
