export default [
  {
    href: "/docs",
    target: "_self",
    sub: false,
    label: "Welcome to the documentation!",
  },
  {
    href: "/docs/playground",
    target: "_self",
    sub: false,
    label: "Playground",
  },
  {
    label: "Installation",
  },
  {
    href: "/docs/installation/installer-linux",
    target: "_self",
    sub: true,
    label: "Installer (GNU/Linux)",
  },
  {
    href: "/docs/installation/installer-windows",
    target: "_self",
    sub: true,
    label: "Installer (Windows Server)",
  },
  {
    href: "/docs/installation/debian",
    target: "_self",
    sub: true,
    label: "Debian/Ubuntu",
  },
  {
    href: "/docs/installation/rpm",
    target: "_self",
    sub: true,
    label: "RHEL/Fedora",
  },
  {
    href: "/docs/installation/docker",
    target: "_self",
    sub: true,
    label: "Docker",
  },
  {
    href: "/docs/installation/package-managers",
    target: "_self",
    sub: true,
    label: "Package managers (community)",
  },
  {
    href: "/docs/installation/manual",
    target: "_self",
    sub: true,
    label: "Manual installation",
  },
  {
    label: "Common use cases",
  },
  {
    href: "/docs/use-cases/static-file-serving",
    target: "_self",
    sub: true,
    label: "Static file serving",
  },
  {
    href: "/docs/use-cases/reverse-proxy",
    target: "_self",
    sub: true,
    label: "Reverse proxying",
  },
  {
    href: "/docs/use-cases/php",
    target: "_self",
    sub: true,
    label: "PHP hosting",
  },
  {
    href: "/docs/use-cases/web-applications",
    target: "_self",
    sub: true,
    label: "Web applications",
  },
  {
    href: "/docs/use-cases/redirecting",
    target: "_self",
    sub: true,
    label: "Redirecting",
  },
  {
    label: "Reference",
  },
  {
    href: "/docs/configuration-kdl",
    target: "_self",
    sub: true,
    label: "Server configuration",
  },
  {
    href: "/docs/configuration",
    target: "_self",
    sub: true,
    label: "Server configuration (legacy)",
  },
  {
    href: "/docs/modules",
    target: "_self",
    sub: true,
    label: "Server modules",
  },
  {
    href: "/docs/observability",
    target: "_self",
    sub: true,
    label: "Observability backends",
  },
  {
    href: "/docs/automatic-tls",
    target: "_self",
    sub: true,
    label: "Automatic TLS",
  },
  {
    href: "/docs/commands",
    target: "_self",
    sub: true,
    label: "Commands",
  },
  {
    href: "/docs/ferrbench",
    target: "_self",
    sub: true,
    label: "FerrBench",
  },
  {
    href: "https://rustdocs-v2.ferron.sh",
    target: "_self",
    sub: true,
    label: "Rust crate documentation",
  },
  {
    href: "https://v1.ferron.sh/docs",
    target: "_self",
    sub: true,
    label: "Ferron 1.x documentation",
  },
];
